nginx:
    image: nosun/nginx:v5
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /opt/data/www:/data/www

php:
    image: nosun/php7:v9
    ports:
      - "9002:9000"
      - "9003:9001"
    links:
      - "mysql"
      - "redis"
    volumes:
      - /opt/data/www:/data/www

mysql:
    image: nosun/mysql
    ports:
      - "3305:3306"
    volumes:
      - /opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rensheng

redis:
    image: nosun/redis
    ports:
      - "6378:6379"
